### ISSUE TITLE
Total Revenue by Date Test

### ISSUE THREAD

**Issue by weilandia** [turingschool/black_thursday_spec_harness#17]
Hey Lovisa,

In this test on Iteration 4, line 12, the date used is only ever in the data for an Invoice Updated At date ("2011-02-27").  Should this method query updated_at dates?  Shouldn't it be created_at dates?

![date_for_revenue](https://cloud.githubusercontent.com/assets/13652979/12403122/091ca3d4-bdef-11e5-9bb4-16a99480546c.jpg)

**Comment by biglovisa** [comment]
Yes, you're right - see this pr https://github.com/turingschool/black_thursday_spec_harness/pull/21/files
